table dim_student
	column student_id
		dataType: string
		summarizeBy: none
		sourceColumn: student_id

	column first_name
		dataType: string
		summarizeBy: none
		sourceColumn: first_name

	column last_name
		dataType: string
		summarizeBy: none
		sourceColumn: last_name

	column student_name
		dataType: string
		summarizeBy: none
		sourceColumn: student_name

	column dob
		dataType: dateTime
		summarizeBy: none
		sourceColumn: dob

	column gender
		dataType: string
		summarizeBy: none
		sourceColumn: gender

	column citizenship
		dataType: string
		summarizeBy: none
		sourceColumn: citizenship

	column postcode
		dataType: string
		summarizeBy: none
		sourceColumn: postcode

	column state
		dataType: string
		summarizeBy: none
		sourceColumn: state

	column home_campus_code
		dataType: string
		summarizeBy: none
		sourceColumn: home_campus_code

	column program_code
		dataType: string
		summarizeBy: none
		sourceColumn: program_code

	column commencing_term
		dataType: string
		summarizeBy: none
		sourceColumn: commencing_term

	column commencing_year
		dataType: int64
		summarizeBy: none
		sourceColumn: commencing_year

	column attendance_type
		dataType: string
		summarizeBy: none
		sourceColumn: attendance_type

	column mode
		dataType: string
		summarizeBy: none
		sourceColumn: mode

	column age_group
		dataType: string
		summarizeBy: none
		sourceColumn: age_group

	column basis_of_admission
		dataType: string
		summarizeBy: none
		sourceColumn: basis_of_admission

	column atar
		dataType: double
		summarizeBy: none
		sourceColumn: atar

	column first_nations
		dataType: string
		summarizeBy: none
		sourceColumn: first_nations

	column disability
		dataType: string
		summarizeBy: none
		sourceColumn: disability

	column nesb
		dataType: string
		summarizeBy: none
		sourceColumn: nesb

	column ses_quartile
		dataType: int64
		summarizeBy: none
		sourceColumn: ses_quartile

	column remoteness
		dataType: string
		summarizeBy: none
		sourceColumn: remoteness

	column low_ses
		dataType: string
		summarizeBy: none
		sourceColumn: low_ses

	column regional_remote
		dataType: string
		summarizeBy: none
		sourceColumn: regional_remote

	column nbf_equity_cohort
		dataType: string
		summarizeBy: none
		sourceColumn: nbf_equity_cohort

	column nbf_category
		dataType: string
		summarizeBy: none
		sourceColumn: nbf_category

	column student_status
		dataType: string
		summarizeBy: none
		sourceColumn: student_status

	column status_term
		dataType: string
		summarizeBy: none
		sourceColumn: status_term

	partition dim_student = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\dim_student.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Selected = Table.SelectColumns(Promoted, {"student_id", "first_name", "last_name", "student_name", "dob", "gender", "citizenship", "postcode", "state", "home_campus_code", "program_code", "commencing_term", "commencing_year", "attendance_type", "mode", "age_group", "basis_of_admission", "atar", "first_nations", "disability", "nesb", "ses_quartile", "remoteness", "low_ses", "regional_remote", "nbf_equity_cohort", "nbf_category", "student_status", "status_term"}),
					Typed = Table.TransformColumnTypes(Selected, {{"student_id", type text}, {"first_name", type text}, {"last_name", type text}, {"student_name", type text}, {"dob", type date}, {"gender", type text}, {"citizenship", type text}, {"postcode", type text}, {"state", type text}, {"home_campus_code", type text}, {"program_code", type text}, {"commencing_term", type text}, {"commencing_year", Int64.Type}, {"attendance_type", type text}, {"mode", type text}, {"age_group", type text}, {"basis_of_admission", type text}, {"atar", type number}, {"first_nations", type text}, {"disability", type text}, {"nesb", type text}, {"ses_quartile", Int64.Type}, {"remoteness", type text}, {"low_ses", type text}, {"regional_remote", type text}, {"nbf_equity_cohort", type text}, {"nbf_category", type text}, {"student_status", type text}, {"status_term", type text}})
				in
					Typed
