table dim_advisor
	column advisor_id
		dataType: string
		summarizeBy: none
		sourceColumn: advisor_id

	column advisor_name
		dataType: string
		summarizeBy: none
		sourceColumn: advisor_name

	column covered_campuses
		dataType: string
		summarizeBy: none
		sourceColumn: covered_campuses

	partition dim_advisor = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\dim_advisor.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Selected = Table.SelectColumns(Promoted, {"advisor_id", "advisor_name", "covered_campuses"}),
					Typed = Table.TransformColumnTypes(Selected, {{"advisor_id", type text}, {"advisor_name", type text}, {"covered_campuses", type text}})
				in
					Typed
