table dim_term
	column term_code
		dataType: string
		summarizeBy: none
		sourceColumn: term_code

	column term_start
		dataType: dateTime
		summarizeBy: none
		sourceColumn: term_start

	column census_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: census_date

	column teaching_weeks
		dataType: int64
		summarizeBy: none
		sourceColumn: teaching_weeks

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column semester
		dataType: string
		summarizeBy: none
		sourceColumn: semester

	column is_current
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_current

	partition dim_term = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\dim_term.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Selected = Table.SelectColumns(Promoted, {"term_code", "term_start", "census_date", "teaching_weeks", "year", "semester", "is_current"}),
					Typed = Table.TransformColumnTypes(Selected, {{"term_code", type text}, {"term_start", type date}, {"census_date", type date}, {"teaching_weeks", Int64.Type}, {"year", Int64.Type}, {"semester", type text}, {"is_current", type logical}})
				in
					Typed
