table fact_enrolment
	column student_id
		dataType: string
		summarizeBy: none
		sourceColumn: student_id

	column unit_code
		dataType: string
		summarizeBy: none
		sourceColumn: unit_code

	column term_code
		dataType: string
		summarizeBy: none
		sourceColumn: term_code

	column campus_code
		dataType: string
		summarizeBy: none
		sourceColumn: campus_code

	column enrolment_status
		dataType: string
		summarizeBy: none
		sourceColumn: enrolment_status

	column grade
		dataType: string
		summarizeBy: none
		sourceColumn: grade

	column mark
		dataType: double
		summarizeBy: none
		sourceColumn: mark

	column eftsl
		dataType: double
		summarizeBy: sum
		sourceColumn: eftsl

	column census_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: census_date

	column passed
		dataType: string
		summarizeBy: none
		sourceColumn: passed

	column eftsl_certified
		dataType: double
		summarizeBy: sum
		sourceColumn: eftsl_certified

	column eftsl_passed
		dataType: double
		summarizeBy: sum
		sourceColumn: eftsl_passed

	measure 'Headcount' = DISTINCTCOUNT(fact_enrolment[student_id])
		formatString: #,0

	measure 'EFTSL Certified' = SUM(fact_enrolment[eftsl_certified])
		formatString: #,0.0

	measure 'EFTSL Passed' = SUM(fact_enrolment[eftsl_passed])
		formatString: #,0.0

	measure 'Success Rate' = DIVIDE([EFTSL Passed], [EFTSL Certified])
		formatString: 0.0%

	measure 'Average Mark' = CALCULATE(AVERAGE(fact_enrolment[mark]), fact_enrolment[mark] >= 0, fact_enrolment[mark] <= 100)
		formatString: 0.0

	measure 'Pre-Census Withdrawals' = CALCULATE(COUNTROWS(fact_enrolment), fact_enrolment[enrolment_status] = "Withdrawn pre-census")
		formatString: #,0

	partition fact_enrolment = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\fact_enrolment.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Selected = Table.SelectColumns(Promoted, {"student_id", "unit_code", "term_code", "campus_code", "enrolment_status", "grade", "mark", "eftsl", "census_date", "passed", "eftsl_certified", "eftsl_passed"}),
					Typed = Table.TransformColumnTypes(Selected, {{"student_id", type text}, {"unit_code", type text}, {"term_code", type text}, {"campus_code", type text}, {"enrolment_status", type text}, {"grade", type text}, {"mark", type number}, {"eftsl", type number}, {"census_date", type date}, {"passed", type text}, {"eftsl_certified", type number}, {"eftsl_passed", type number}})
				in
					Typed
