table fact_alert
	column alert_id
		dataType: string
		summarizeBy: none
		sourceColumn: alert_id

	column student_id
		dataType: string
		summarizeBy: none
		sourceColumn: student_id

	column term_code
		dataType: string
		summarizeBy: none
		sourceColumn: term_code

	column week_number
		dataType: int64
		summarizeBy: none
		sourceColumn: week_number

	column raised_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: raised_date

	column reason_code
		dataType: string
		summarizeBy: none
		sourceColumn: reason_code

	column actioned_case_id
		dataType: string
		summarizeBy: none
		sourceColumn: actioned_case_id

	column actioned_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: actioned_date

	column contact_outcome
		dataType: string
		summarizeBy: none
		sourceColumn: contact_outcome

	column case_status
		dataType: string
		summarizeBy: none
		sourceColumn: case_status

	column lifecycle_status
		dataType: string
		summarizeBy: none
		sourceColumn: lifecycle_status

	column days_to_action
		dataType: int64
		summarizeBy: sum
		sourceColumn: days_to_action

	measure 'Alerts Raised' = COUNTROWS(fact_alert)
		formatString: #,0

	measure 'Alerts Actioned' = CALCULATE(COUNTROWS(fact_alert), fact_alert[lifecycle_status] IN {"Actioned - case opened", "Covered by same-term case"})
		formatString: #,0

	measure 'Alert Action Rate' = DIVIDE([Alerts Actioned], [Alerts Raised])
		formatString: 0.0%

	measure 'Median Days To Action' = MEDIAN(fact_alert[days_to_action])
		formatString: 0.0

	partition fact_alert = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\fact_alert.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Selected = Table.SelectColumns(Promoted, {"alert_id", "student_id", "term_code", "week_number", "raised_date", "reason_code", "actioned_case_id", "actioned_date", "contact_outcome", "case_status", "lifecycle_status", "days_to_action"}),
					Typed = Table.TransformColumnTypes(Selected, {{"alert_id", type text}, {"student_id", type text}, {"term_code", type text}, {"week_number", Int64.Type}, {"raised_date", type date}, {"reason_code", type text}, {"actioned_case_id", type text}, {"actioned_date", type date}, {"contact_outcome", type text}, {"case_status", type text}, {"lifecycle_status", type text}, {"days_to_action", Int64.Type}})
				in
					Typed
