table mart_triage_current
	column student_id
		dataType: string
		summarizeBy: none
		sourceColumn: student_id

	column student_name
		dataType: string
		summarizeBy: none
		sourceColumn: student_name

	column program_code
		dataType: string
		summarizeBy: none
		sourceColumn: program_code

	column program_name
		dataType: string
		summarizeBy: none
		sourceColumn: program_name

	column home_campus_code
		dataType: string
		summarizeBy: none
		sourceColumn: home_campus_code

	column mode
		dataType: string
		summarizeBy: none
		sourceColumn: mode

	column attendance_type
		dataType: string
		summarizeBy: none
		sourceColumn: attendance_type

	column nbf_equity_cohort
		dataType: string
		summarizeBy: none
		sourceColumn: nbf_equity_cohort

	column first_nations
		dataType: string
		summarizeBy: none
		sourceColumn: first_nations

	column disability
		dataType: string
		summarizeBy: none
		sourceColumn: disability

	column is_commencing
		dataType: string
		summarizeBy: none
		sourceColumn: is_commencing

	column first_alert_week
		dataType: int64
		summarizeBy: none
		sourceColumn: first_alert_week

	column latest_alert_week
		dataType: int64
		summarizeBy: none
		sourceColumn: latest_alert_week

	column alert_count
		dataType: int64
		summarizeBy: sum
		sourceColumn: alert_count

	column reasons
		dataType: string
		summarizeBy: none
		sourceColumn: reasons

	column contacted
		dataType: int64
		summarizeBy: sum
		sourceColumn: contacted

	column case_status
		dataType: string
		summarizeBy: none
		sourceColumn: case_status

	column contact_outcome
		dataType: string
		summarizeBy: none
		sourceColumn: contact_outcome

	column logins_last2wk
		dataType: int64
		summarizeBy: sum
		sourceColumn: logins_last2wk

	column missed_last2wk
		dataType: int64
		summarizeBy: sum
		sourceColumn: missed_last2wk

	column priority_tier
		dataType: string
		summarizeBy: none
		sourceColumn: priority_tier

	column advisor_id
		dataType: string
		summarizeBy: none
		sourceColumn: advisor_id

	measure 'Students On Triage List' = DISTINCTCOUNT(mart_triage_current[student_id])
		formatString: #,0

	measure 'P1 Students' = CALCULATE(DISTINCTCOUNT(mart_triage_current[student_id]), LEFT(mart_triage_current[priority_tier], 2) = "P1")
		formatString: #,0

	partition mart_triage_current = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\mart_triage_current.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Selected = Table.SelectColumns(Promoted, {"student_id", "student_name", "program_code", "program_name", "home_campus_code", "mode", "attendance_type", "nbf_equity_cohort", "first_nations", "disability", "is_commencing", "first_alert_week", "latest_alert_week", "alert_count", "reasons", "contacted", "case_status", "contact_outcome", "logins_last2wk", "missed_last2wk", "priority_tier", "advisor_id"}),
					Typed = Table.TransformColumnTypes(Selected, {{"student_id", type text}, {"student_name", type text}, {"program_code", type text}, {"program_name", type text}, {"home_campus_code", type text}, {"mode", type text}, {"attendance_type", type text}, {"nbf_equity_cohort", type text}, {"first_nations", type text}, {"disability", type text}, {"is_commencing", type text}, {"first_alert_week", Int64.Type}, {"latest_alert_week", Int64.Type}, {"alert_count", Int64.Type}, {"reasons", type text}, {"contacted", Int64.Type}, {"case_status", type text}, {"contact_outcome", type text}, {"logins_last2wk", Int64.Type}, {"missed_last2wk", Int64.Type}, {"priority_tier", type text}, {"advisor_id", type text}})
				in
					Typed
