table mart_engagement_trend
	column term_code
		dataType: string
		summarizeBy: none
		sourceColumn: term_code

	column week_number
		dataType: int64
		summarizeBy: none
		sourceColumn: week_number

	column mode
		dataType: string
		summarizeBy: none
		sourceColumn: mode

	column nbf_equity_cohort
		dataType: string
		summarizeBy: none
		sourceColumn: nbf_equity_cohort

	column students
		dataType: int64
		summarizeBy: sum
		sourceColumn: students

	column avg_logins
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_logins

	column missed_rate
		dataType: double
		summarizeBy: sum
		sourceColumn: missed_rate

	partition mart_engagement_trend = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\mart_engagement_trend.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Selected = Table.SelectColumns(Promoted, {"term_code", "week_number", "mode", "nbf_equity_cohort", "students", "avg_logins", "missed_rate"}),
					Typed = Table.TransformColumnTypes(Selected, {{"term_code", type text}, {"week_number", Int64.Type}, {"mode", type text}, {"nbf_equity_cohort", type text}, {"students", Int64.Type}, {"avg_logins", type number}, {"missed_rate", type number}})
				in
					Typed
